# Generated by Django 4.2.17 on 2025-01-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_reply_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='parent_comment',
            new_name='comment',
        ),
    ]
